<a href="https://colab.research.google.com/github/SaChIn5419/Data-science-workshop-/blob/main/math_for_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Define matrix A and vector B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([1, 2, 3])

# 1. Matrix-Vector Multiplication
matrix_vector_product = np.dot(A, B)

# 2. Trace of matrix A
trace_A = np.trace(A)

# 3. Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Outputs
print("Matrix A:\n", A)
print("Vector B:\n", B)
print("Matrix-Vector Product A x B:\n", matrix_vector_product)
print("Trace of Matrix A:", trace_A)
print("Eigenvalues of Matrix A:", eigenvalues)
print("Eigenvectors of Matrix A:\n", eigenvectors)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector B:
 [1 2 3]
Matrix-Vector Product A x B:
 [14 32 50]
Trace of Matrix A: 15
Eigenvalues of Matrix A: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors of Matrix A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [7]:
# Replace the last row of A
A[2] = [10, 11, 12]

# Compute determinant
determinant_A = np.linalg.det(A)

# Check singularity
is_singular = np.isclose(determinant_A, 0)

# Outputs
print("Updated Matrix A:\n", A)
print("Determinant of Updated A:", determinant_A)
print("Is Updated A Singular?", "Yes" if is_singular else "No")


Updated Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Determinant of Updated A: 0.0
Is Updated A Singular? Yes


In [8]:
# Check for invertibility
if not is_singular:
    inverse_A = np.linalg.inv(A)
    print("Inverse of Updated A:\n", inverse_A)
else:
    print("Updated A is singular; no inverse exists.")

# Solve A * X = B
if not is_singular:
    X = np.linalg.solve(A, B)
    print("Solution to A * X = B:\n", X)
else:
    print("Cannot solve A * X = B as A is singular.")


Updated A is singular; no inverse exists.
Cannot solve A * X = B as A is singular.


In [9]:
import numpy as np

# Define updated matrix A and column vector B
A = np.array([[1, 2, 3], [4, 5, 6], [10, 11, 12]])  # Updated A
B = np.array([[1], [2], [3]])  # Column vector B

# Check determinant
determinant_A = np.linalg.det(A)
is_singular = np.isclose(determinant_A, 0)

if is_singular:
    print("Updated A is singular; no inverse exists.")
    print("Cannot solve A * X = B as A is singular.")
else:
    inverse_A = np.linalg.inv(A)
    print("Inverse of Updated A:\n", inverse_A)

    # Solve A * X = B
    X = np.linalg.solve(A, B)
    print("Solution to A * X = B:\n", X)

# Alternative: Least Squares Solution
X_least_squares = np.linalg.lstsq(A, B, rcond=None)[0]
print("Least Squares Solution X:\n", X_least_squares)


Updated A is singular; no inverse exists.
Cannot solve A * X = B as A is singular.
Least Squares Solution X:
 [[-0.28571429]
 [ 0.07142857]
 [ 0.42857143]]


In [4]:
# Generate random 4x4 matrix C
C = np.random.randint(1, 21, size=(4, 4))

# Compute rank
rank_C = np.linalg.matrix_rank(C)

# Extract submatrix
submatrix = C[:2, -2:]

# Compute Frobenius norm
frobenius_norm = np.linalg.norm(C, 'fro')

# Check matrix multiplication validity
if A.shape[1] == C.shape[0]:
    product = np.dot(A, C[:3, :3])  # Trim C if needed
    print("Matrix Multiplication A x C:\n", product)
else:
    print("Matrix multiplication not valid. Adjusting dimensions of C.")
    C = C[:3, :3]

# Outputs
print("Matrix C:\n", C)
print("Rank of C:", rank_C)
print("Submatrix (first 2 rows, last 2 columns):\n", submatrix)
print("Frobenius Norm of C:", frobenius_norm)


Matrix multiplication not valid. Adjusting dimensions of C.
Matrix C:
 [[16 14 20]
 [10 15 19]
 [12  6  3]]
Rank of C: 4
Submatrix (first 2 rows, last 2 columns):
 [[20  4]
 [19  4]]
Frobenius Norm of C: 46.357307945997036


In [5]:
# Dataset as a matrix
D = np.array([[3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10],
              [1, 3, 5, 7, 9],
              [4, 6, 8, 10, 12],
              [5, 7, 9, 11, 13]])

# Standardize D
mean = np.mean(D, axis=0)
std_dev = np.std(D, axis=0)
D_standardized = (D - mean) / std_dev

# Covariance matrix
cov_matrix = np.cov(D_standardized.T)

# PCA: Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Reduce to 2 components
D_pca = np.dot(D_standardized, eigenvectors[:, :2])

# Outputs
print("Standardized D:\n", D_standardized)
print("Covariance Matrix:\n", cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("D reduced to 2 Principal Components:\n", D_pca)


Standardized D:
 [[ 0.          0.          0.          0.          0.        ]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [-1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [ 0.70710678  0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356]]
Covariance Matrix:
 [[1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]]
Eigenvalues:
 [0.   6.25 0.   0.   0.  ]
Eigenvectors:
 [[-0.89442719  0.4472136   0.          0.          0.        ]
 [ 0.2236068   0.4472136  -0.5        -0.5        -0.5       ]
 [ 0.2236068   0.4472136   0.83333333 -0.16666667 -0.16666667]
 [ 0.2236068   0.4472136  -0.16666667  0.83333333 -0.16666667]
 [ 0.2236068   0.4472136  -0.16666667 -0.16666667  0.83333333]]
D reduced to 2 Principal Components:
 [[ 0.00000000e+00  0.00000000e+00]
 [-2.11442546e-16 -1.58113883e+00]
 [-4.22885092e-16 -3.16227